version: "3.7"
services:
  backend:
    build: ./backend
    tty: true
    command: sh -c "npm install && npm run start:dev"
    ports:
      - "15000:3000"
    volumes:
      - type: bind
        source: ./backend
        target: /myapp
  mysql:
    image: mysql/mysql-server:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - '13306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: develop
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - /var/lib/mysql
  frontend:
    build: ./frontend
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/usr/src/app
    command: sh -c 'npm install && npm run start:dev'
    ports:
      - '13000:3000'
    tty: true
  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - 80:80
    tty: true
    restart: always
    depends_on:
      - frontend
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  redis:
    image: redis:latest
    ports:
      - 6379:6379